### ISSUE TITLE
How do I generate an executable with this using Cargo?

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [Devolutions/CMakeRust#5]
I've noticed that there is a demonstration of using rustc to build an executable under `/hello/`, but `/crates/test-bin` seems to not be CMake compatible. Is there a solution that exists using this project or will I have to look elsewhere?

**Comment by ekse** [comment]
This project makes it is possible to generate an executable with CMake that includes rust code. We have a complete example in the following repo and a blog post that details the steps to use it. We should move the example in this repository, I'm adding this to my todo. 

https://github.com/ekse/cmake_rust_sample
https://blog.devolutions.net/2018/06/insider-series-using-rust-code-in-a-cc-project-with-cmake

Let me know if this helps or if you run into issues.

**Comment by ekse** [comment]
Closing as inactive, feel free to reopen if needed.
